### ISSUE TITLE
First Run Error 

### ISSUE THREAD

**Issue by demaul** [evinowen/tome#78]
First run of Tome, version 0.7.2, error loading config.json

Initially setup name, email, generated public key, automatic push (on)

![image](https://user-images.githubusercontent.com/54587015/225137734-b1212cb1-751d-46dd-a4e2-116f15d87492.png)

Restarted Tome and it worked great.

**Comment by evinowen** [comment]
This should be resolved with PR #82 and release https://github.com/evinowen/tome/releases/tag/0.7.5
